# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-android:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      KEY_STORE: ${{ secrets.KEY_STORE }}
      KEY_PATH: ${{ github.workspace }}/upload-keystore.jks
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      ALIAS_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Create key file
      run: echo $KEY_STORE | base64 -di > ./upload-keystore.jks
        
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.4'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk --release --split-per-abi
    - run: flutter build appbundle

    # Make appbundle downloadable
    - name: Upload artefato
      uses: actions/upload-artifact@v2
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.apk
    
  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - uses: subosito/flutter-action@v2
  #     with:
  #       flutter-version: '2.10.4'
  #       architecture: x64
  #   - run: flutter pub get
  #   - run: flutter test
  #   - run: flutter build ios --release --no-codesign
